# Generated by Django 6.0 on 2025-12-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_contact_created_at_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
