# Generated by Django 6.0 on 2025-12-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_contact_latitude_contact_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
